INSERT INTO
	%1.tag_TerminalsTable
	(
		%1.tag_TerminalsTable.readerId,
		%1.tag_TerminalsTable.type,
		%1.tag_TerminalsTable.readerExpId,
		%1.tag_TerminalsTable.active,
		%1.tag_TerminalsTable.deactiveByDateTime,
		%1.tag_TerminalsTable.deactiveStartDateTime,
		%1.tag_TerminalsTable.deactiveStopDateTime,
		%1.tag_TerminalsTable.UUID
	)
	VALUES
	(
		%2,
		%3,
		%4,
		%5,
		%6,
		%7,
		%8,
		'%9'
	)
