INSERT INTO
	%1.HolidaysGroupsTable
	(
		%1.HolidaysGroupsTable.code,
		%1.HolidaysGroupsTable.uuid01_HolidaysSetsTableUuid,
		%1.HolidaysGroupsTable.uuid02_HolidaysSetsTableUuid,
		%1.HolidaysGroupsTable.uuid03_HolidaysSetsTableUuid,
		%1.HolidaysGroupsTable.uuid04_HolidaysSetsTableUuid,
		%1.HolidaysGroupsTable.uuid05_HolidaysSetsTableUuid,
		%1.HolidaysGroupsTable.UUID
	)
	VALUES
	(
		%2,
		%3,
		%4,
		%5,
		%6,
		%7,
		'%8'
	)
