INSERT INTO
	%1.AccessShiftsTable
	(
		%1.AccessShiftsTable.code,
		%1.AccessShiftsTable.type,
		%1.AccessShiftsTable.uuidSat__AccessTimezonesTableUuid,
		%1.AccessShiftsTable.uuidSun__AccessTimezonesTableUuid,
		%1.AccessShiftsTable.uuidMon__AccessTimezonesTableUuid,
		%1.AccessShiftsTable.uuidTue__AccessTimezonesTableUuid,
		%1.AccessShiftsTable.uuidWed__AccessTimezonesTableUuid,
		%1.AccessShiftsTable.uuidThu__AccessTimezonesTableUuid,
		%1.AccessShiftsTable.uuidFri__AccessTimezonesTableUuid,
		%1.AccessShiftsTable.uuidHol__AccessTimezonesTableUuid,
		%1.AccessShiftsTable.UUID
	)
	VALUES
	(
		%2,
		%3,
		%4,
		%5,
		%6,
		%7,
		%8,
		%9,
		%10,
		%11,
		'%12'
	)
