INSERT INTO
	%1.AccessTimezonesTable
	(
		%1.AccessTimezonesTable.code,
		%1.AccessTimezonesTable.uuid01__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid02__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid03__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid04__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid05__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid06__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid07__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid08__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid09__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid10__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid11__TimezonesTableUuid,
		%1.AccessTimezonesTable.uuid12__TimezonesTableUuid,
		%1.AccessTimezonesTable.UUID
	)
	VALUES
	(
		%2,
		%3,
		%4,
		%5,
		%6,
		%7,
		%8,
		%9,
		%10,
		%11,
		%12,
		%13,
		%14,
		'%15'
	)
